"""Exact symbolic multigraded resolutions for small Stanley-Reisner fans.

The Parameter-Golf trainer cannot call a computer-algebra system inside the
inner loop, but the fan used by the CCA bridge is tiny and combinatorial.  This
module computes exact finite invariants for that fan:

* the Stanley-Reisner nonface generators;
* Hochster multigraded Betti numbers of ``k[Delta]`` over ``F_2``;
* Taylor free-resolution ranks for the monomial ideal ``I_Delta``.

The minimal Betti table is symbolic and exact for the finite simplicial complex
being audited.  The Taylor resolution is generally nonminimal, but it is a full
free resolution by construction and gives a useful nonminimality pressure.
"""

from __future__ import annotations

import functools
import math
from dataclasses import dataclass
from itertools import combinations


@dataclass(frozen=True)
class SymbolicResolutionMetrics:
    num_vertices: int
    nonface_generator_count: int
    minimal_total_betti: int
    minimal_positive_betti: int
    taylor_total_rank_log2: float
    taylor_positive_rank_log2: float
    taylor_boundary_terms_log2: float
    nonminimality_log2: float
    projective_dimension: int
    regularity: int
    betti0: int
    betti1: int
    betti2: int
    top_multidegree_cardinality: int
    betti_entropy: float


def mask_vertices(mask: int, num_vertices: int | None = None) -> tuple[int, ...]:
    """Return the ordered vertices contained in a squarefree monomial mask."""

    width = int(num_vertices) if num_vertices is not None else max(1, int(mask).bit_length())
    return tuple(index for index in range(width) if int(mask) & (1 << index))


def cyclic_flag_faces(num_vertices: int) -> frozenset[int]:
    """Return the flag complex generated by a cyclic fan graph.

    Faces are encoded as bitmasks.  The empty face is included.  For the cyclic
    graph with ``n >= 4`` there are no triangles; the generic clique enumerator
    is retained because it makes the exact complex definition explicit.
    """

    n = max(1, int(num_vertices))
    allowed_edges: set[int] = set()
    for i in range(n):
        allowed_edges.add((1 << i) | (1 << ((i + 1) % n)))
    faces: set[int] = {0}
    for mask in range(1, 1 << n):
        vertices = [i for i in range(n) if mask & (1 << i)]
        ok = True
        for a, b in combinations(vertices, 2):
            edge = (1 << a) | (1 << b)
            if edge not in allowed_edges:
                ok = False
                break
        if ok:
            faces.add(mask)
    return frozenset(faces)


@functools.lru_cache(maxsize=64)
def cyclic_flag_face_rows(num_vertices: int) -> tuple[tuple[int, int, int], ...]:
    """Rows ``(dimension, mask, cardinality)`` for the cyclic flag complex."""

    faces = cyclic_flag_faces(num_vertices)
    rows = []
    for mask in sorted(faces, key=lambda item: (item.bit_count(), item)):
        cardinality = int(mask).bit_count()
        dimension = cardinality - 1
        rows.append((int(dimension), int(mask), int(cardinality)))
    return tuple(rows)


def stanley_reisner_nonfaces(num_vertices: int, faces: frozenset[int]) -> tuple[int, ...]:
    """Return minimal squarefree nonfaces of a complex encoded by bitmasks."""

    n = max(1, int(num_vertices))
    nonfaces: list[int] = []
    for mask in range(1, 1 << n):
        if mask in faces:
            continue
        minimal = True
        sub = (mask - 1) & mask
        while sub:
            if sub not in faces:
                minimal = False
                break
            sub = (sub - 1) & mask
        if minimal:
            nonfaces.append(mask)
    return tuple(sorted(nonfaces, key=lambda item: (item.bit_count(), item)))


@functools.lru_cache(maxsize=64)
def cyclic_stanley_reisner_generator_masks(num_vertices: int) -> tuple[int, ...]:
    """Minimal squarefree monomial generators of the cyclic fan SR ideal."""

    n = max(1, int(num_vertices))
    return stanley_reisner_nonfaces(n, cyclic_flag_faces(n))


@functools.lru_cache(maxsize=64)
def cyclic_taylor_multidegree_counts(num_vertices: int) -> tuple[tuple[int, int, int], ...]:
    """Compressed exact Taylor-resolution multidegree counts.

    Each tuple is ``(homological_degree, squarefree_lcm_mask, multiplicity)``.
    This represents every Taylor basis element without enumerating all
    ``2^g`` subsets of the monomial generators.
    """

    generators = cyclic_stanley_reisner_generator_masks(num_vertices)
    counts: dict[int, dict[int, int]] = {0: {0: 1}}
    for generator in generators:
        updated = {degree: values.copy() for degree, values in counts.items()}
        for degree, values in counts.items():
            target = updated.setdefault(degree + 1, {})
            for mask, multiplicity in values.items():
                lcm_mask = mask | generator
                target[lcm_mask] = target.get(lcm_mask, 0) + multiplicity
        counts = updated
    rows: list[tuple[int, int, int]] = []
    for degree in sorted(counts):
        if degree == 0:
            continue
        for mask, multiplicity in sorted(counts[degree].items()):
            rows.append((int(degree), int(mask), int(multiplicity)))
    return tuple(rows)


@functools.lru_cache(maxsize=64)
def cyclic_taylor_rank_rows(num_vertices: int) -> tuple[tuple[int, int, int], ...]:
    """Exact Taylor ranks and differential term counts by homological degree.

    Each row is ``(degree, rank, outgoing_boundary_terms)`` for the Taylor
    resolution of ``S / I_Delta``.  It is computed from the number of minimal
    Stanley-Reisner generators and therefore represents the full Taylor
    complex without enumerating every basis element when only aggregate ranks
    are needed.
    """

    generator_count = len(cyclic_stanley_reisner_generator_masks(num_vertices))
    rows = [(0, 1, 0)]
    for degree in range(1, generator_count + 1):
        rank = math.comb(generator_count, degree)
        rows.append((int(degree), int(rank), int(degree * rank)))
    return tuple(rows)


def _simplices_by_dim(faces: frozenset[int], support: int) -> dict[int, list[int]]:
    out: dict[int, list[int]] = {}
    for face in faces:
        if face == 0 or face & ~support:
            continue
        dim = face.bit_count() - 1
        out.setdefault(dim, []).append(face)
    return out


def _boundary_rank(domain: list[int], codomain: list[int]) -> int:
    """Rank over F2 of the simplicial boundary matrix."""

    if not domain or not codomain:
        return 0
    row_index = {face: idx for idx, face in enumerate(codomain)}
    rows = [0 for _ in codomain]
    for col, simplex in enumerate(domain):
        bits = [i for i in range(simplex.bit_length()) if simplex & (1 << i)]
        for vertex in bits:
            boundary_face = simplex & ~(1 << vertex)
            idx = row_index.get(boundary_face)
            if idx is not None:
                rows[idx] ^= 1 << col
    return _rank_bitrows(rows)


def _rank_bitrows(rows: list[int]) -> int:
    basis: dict[int, int] = {}
    rank = 0
    for value in rows:
        x = int(value)
        while x:
            pivot = x.bit_length() - 1
            if pivot in basis:
                x ^= basis[pivot]
            else:
                basis[pivot] = x
                rank += 1
                break
    return rank


def reduced_homology_dim_f2(faces: frozenset[int], support: int, q: int) -> int:
    """Reduced homology dimension of the induced subcomplex on ``support``."""

    simplices = _simplices_by_dim(faces, support)
    vertex_count = len(simplices.get(0, []))
    if q == -1:
        return 1 if vertex_count == 0 else 0
    if q < -1:
        return 0
    n_q = len(simplices.get(q, []))
    if n_q == 0:
        return 0
    rank_boundary_q = 0 if q == 0 else _boundary_rank(simplices.get(q, []), simplices.get(q - 1, []))
    rank_boundary_next = _boundary_rank(simplices.get(q + 1, []), simplices.get(q, []))
    homology = n_q - rank_boundary_q - rank_boundary_next
    if q == 0 and vertex_count > 0:
        homology -= 1
    return max(0, int(homology))


@functools.lru_cache(maxsize=64)
def cyclic_stanley_reisner_resolution_metrics(num_vertices: int) -> SymbolicResolutionMetrics:
    """Exact symbolic resolution metrics for the cyclic fan complex."""

    n = max(1, int(num_vertices))
    faces = cyclic_flag_faces(n)
    nonfaces = cyclic_stanley_reisner_generator_masks(n)
    betti: dict[tuple[int, int], int] = {(0, 0): 1}
    for support in range(1, 1 << n):
        support_size = support.bit_count()
        for i in range(0, support_size + 1):
            q = support_size - i - 1
            dim = reduced_homology_dim_f2(faces, support, q)
            if dim:
                betti[(i, support)] = dim

    total_by_homological: dict[int, int] = {}
    for (degree, _support), value in betti.items():
        total_by_homological[degree] = total_by_homological.get(degree, 0) + value
    positive_betti = sum(value for (degree, _support), value in betti.items() if degree > 0)
    minimal_total = sum(betti.values())
    projective_dimension = max(total_by_homological, default=0)
    regularity = 0
    top_cardinality = 0
    for (degree, support), value in betti.items():
        if value <= 0:
            continue
        cardinality = support.bit_count()
        regularity = max(regularity, cardinality - degree)
        top_cardinality = max(top_cardinality, cardinality)

    generator_count = len(nonfaces)
    # Taylor resolution of S/I has F_0=S plus one basis element for every
    # nonempty subset of the monomial generators.
    taylor_positive_rank_log2 = float(generator_count)
    taylor_total_rank_log2 = math.log2(1.0 + 2.0**generator_count)
    if generator_count == 0:
        boundary_terms = 0.0
    else:
        # Sum_{p>=1} p C(g,p) = g 2^{g-1}.
        boundary_terms = float(generator_count) * (2.0 ** max(generator_count - 1, 0))
    taylor_boundary_terms_log2 = math.log2(max(boundary_terms, 1.0))
    nonminimality = max(0.0, (1.0 + 2.0**generator_count) - float(minimal_total))
    nonminimality_log2 = math.log2(max(nonminimality, 1.0))
    masses = [float(value) for value in total_by_homological.values() if value > 0]
    mass_sum = sum(masses)
    if mass_sum > 0.0 and len(masses) > 1:
        probs = [value / mass_sum for value in masses]
        entropy = -sum(p * math.log(p) for p in probs) / math.log(len(probs))
    else:
        entropy = 0.0

    return SymbolicResolutionMetrics(
        num_vertices=n,
        nonface_generator_count=generator_count,
        minimal_total_betti=int(minimal_total),
        minimal_positive_betti=int(positive_betti),
        taylor_total_rank_log2=float(taylor_total_rank_log2),
        taylor_positive_rank_log2=float(taylor_positive_rank_log2),
        taylor_boundary_terms_log2=float(taylor_boundary_terms_log2),
        nonminimality_log2=float(nonminimality_log2),
        projective_dimension=int(projective_dimension),
        regularity=int(regularity),
        betti0=int(total_by_homological.get(0, 0)),
        betti1=int(total_by_homological.get(1, 0)),
        betti2=int(total_by_homological.get(2, 0)),
        top_multidegree_cardinality=int(top_cardinality),
        betti_entropy=float(entropy),
    )


@functools.lru_cache(maxsize=64)
def cyclic_stanley_reisner_betti_rows(num_vertices: int) -> tuple[tuple[int, int, int, int], ...]:
    """Exact Hochster Betti rows ``(i, support_mask, support_size, beta)``."""

    n = max(1, int(num_vertices))
    faces = cyclic_flag_faces(n)
    rows: list[tuple[int, int, int, int]] = [(0, 0, 0, 1)]
    for support in range(1, 1 << n):
        support_size = support.bit_count()
        for i in range(0, support_size + 1):
            q = support_size - i - 1
            dim = reduced_homology_dim_f2(faces, support, q)
            if dim:
                rows.append((int(i), int(support), int(support_size), int(dim)))
    return tuple(rows)


def cyclic_stanley_reisner_resolution_dict(num_vertices: int) -> dict[str, float]:
    metrics = cyclic_stanley_reisner_resolution_metrics(num_vertices)
    return {
        "symbolic_resolution_num_vertices": float(metrics.num_vertices),
        "symbolic_resolution_nonface_generator_count": float(metrics.nonface_generator_count),
        "symbolic_resolution_minimal_total_betti": float(metrics.minimal_total_betti),
        "symbolic_resolution_minimal_positive_betti": float(metrics.minimal_positive_betti),
        "symbolic_resolution_taylor_total_rank_log2": float(metrics.taylor_total_rank_log2),
        "symbolic_resolution_taylor_positive_rank_log2": float(metrics.taylor_positive_rank_log2),
        "symbolic_resolution_taylor_boundary_terms_log2": float(metrics.taylor_boundary_terms_log2),
        "symbolic_resolution_nonminimality_log2": float(metrics.nonminimality_log2),
        "symbolic_resolution_projective_dimension": float(metrics.projective_dimension),
        "symbolic_resolution_regularity": float(metrics.regularity),
        "symbolic_resolution_betti0": float(metrics.betti0),
        "symbolic_resolution_betti1": float(metrics.betti1),
        "symbolic_resolution_betti2": float(metrics.betti2),
        "symbolic_resolution_top_multidegree_cardinality": float(metrics.top_multidegree_cardinality),
        "symbolic_resolution_betti_entropy": float(metrics.betti_entropy),
    }


def cyclic_stanley_reisner_resolution_certificate(num_vertices: int) -> dict[str, object]:
    """Return a machine-readable exact finite CCA/topology certificate.

    The certificate is intended for periodic sidecar analyses.  It records the
    actual finite combinatorial objects used to audit the train-time
    differentiable losses: faces, Stanley-Reisner generators, Hochster Betti
    rows, compressed Taylor multidegrees, and exact Taylor rank/boundary counts.
    """

    n = max(1, int(num_vertices))
    metrics = cyclic_stanley_reisner_resolution_metrics(n)
    face_rows = cyclic_flag_face_rows(n)
    nonfaces = cyclic_stanley_reisner_generator_masks(n)
    betti_rows = cyclic_stanley_reisner_betti_rows(n)
    taylor_rows = cyclic_taylor_multidegree_counts(n)
    taylor_rank_rows = cyclic_taylor_rank_rows(n)

    def monomial(mask: int) -> str:
        vertices = mask_vertices(mask, n)
        if not vertices:
            return "1"
        return "*".join(f"x_{index}" for index in vertices)

    betti_table: dict[str, int] = {}
    for degree, _support, support_size, beta in betti_rows:
        key = f"{int(degree)}:{int(support_size)}"
        betti_table[key] = betti_table.get(key, 0) + int(beta)

    taylor_rank_by_degree = {
        str(int(degree)): int(rank) for degree, rank, _boundary_terms in taylor_rank_rows
    }
    taylor_boundary_terms_by_degree = {
        str(int(degree)): int(boundary_terms)
        for degree, _rank, boundary_terms in taylor_rank_rows
    }

    return {
        "kind": "cyclic_stanley_reisner_symbolic_resolution_certificate",
        "field": "F_2",
        "num_vertices": int(n),
        "vertices": list(range(n)),
        "faces": [
            {
                "dimension": int(dimension),
                "mask": int(mask),
                "vertices": list(mask_vertices(mask, n)),
                "monomial": monomial(mask),
            }
            for dimension, mask, _cardinality in face_rows
        ],
        "minimal_nonface_generators": [
            {
                "mask": int(mask),
                "vertices": list(mask_vertices(mask, n)),
                "degree": int(mask).bit_count(),
                "monomial": monomial(mask),
            }
            for mask in nonfaces
        ],
        "hochster_betti_rows": [
            {
                "homological_degree": int(degree),
                "support_mask": int(support),
                "support_vertices": list(mask_vertices(support, n)),
                "support_size": int(support_size),
                "beta": int(beta),
            }
            for degree, support, support_size, beta in betti_rows
        ],
        "betti_table_by_homological_degree_and_support_size": [
            {
                "homological_degree": int(key.split(":")[0]),
                "support_size": int(key.split(":")[1]),
                "beta_total": int(value),
            }
            for key, value in sorted(
                betti_table.items(),
                key=lambda item: (int(item[0].split(":")[0]), int(item[0].split(":")[1])),
            )
        ],
        "taylor_multidegree_counts": [
            {
                "homological_degree": int(degree),
                "lcm_mask": int(mask),
                "lcm_vertices": list(mask_vertices(mask, n)),
                "lcm_support_size": int(mask).bit_count(),
                "multiplicity": int(multiplicity),
                "monomial": monomial(mask),
            }
            for degree, mask, multiplicity in taylor_rows
        ],
        "taylor_rank_by_homological_degree": taylor_rank_by_degree,
        "taylor_boundary_terms_by_homological_degree": taylor_boundary_terms_by_degree,
        "dg_algebra": {
            "basis": "Taylor exterior basis e_A over subsets of Stanley-Reisner generators",
            "product": "e_A * e_B = e_{A union B} for disjoint generator subsets, zero otherwise over F_2 signs",
            "differential": "Taylor differential with lcm monomial quotients",
            "augmentation_ideal_generator_count": int(metrics.nonface_generator_count),
            "d_squared_zero": True,
            "leibniz_rule": True,
        },
        "metrics": cyclic_stanley_reisner_resolution_dict(n),
    }
