#!/usr/bin/env bash
# Install exact CAS backends for ToricGT.
#
# Targets:
#   - SageMath: preferred in the ToricGT Conda env; fallback is a ToricGT-named
#     Sage env with a wrapper installed into the ToricGT env.
#   - Macaulay2: Ubuntu apt package, with an M2 wrapper installed into the
#     ToricGT env when needed.
#   - Supporting toric/tropical tools: gfan, Singular, Normaliz/PyNormaliz,
#     TOPCOM, 4ti2, LattE integrale, lrslib, nauty, and polymake where
#     available from Ubuntu apt or conda-forge.
#
# This script is intentionally strict: the final verification runs the actual
# CAS-backed ToricGT certificate builder with --require-cas.

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

TORICGT_ENV="tokengt"
SAGE_FALLBACK_ENV="toricgt-sage"
ASSUME_YES=1
INSTALL_SAGE=1
INSTALL_MACAULAY2=1
INSTALL_EXTRAS=1
VERIFY=1
APT_UPDATE=1

usage() {
  cat <<'USAGE'
Usage:
  scripts/install_cas_backends.sh [options]

Options:
  --env NAME                 Conda env used for ToricGT commands (default: tokengt)
  --sage-env NAME            Fallback Sage env name if Sage cannot solve in --env (default: toricgt-sage)
  --no-sage                  Do not install SageMath
  --no-macaulay2             Do not install Macaulay2
  --no-extras                Do not install/check supporting toric tools
  --no-apt-update            Skip apt-get update before installing Macaulay2
  --no-verify                Skip final ToricGT CAS verification
  --yes                      Noninteractive installs (default)
  --no-yes                   Let installers prompt
  -h, --help                 Show this help

Notes:
  - SageMath is installed from conda-forge.
  - Macaulay2 is installed from Ubuntu apt because conda-forge does not provide
    a macaulay2 package on this machine.
  - Supporting tools are installed opportunistically: gfan, Normaliz, TOPCOM,
    4ti2, LattE integrale, lrslib, nauty, polymake, and Singular when provided
    by apt/conda.
  - If Sage cannot be installed directly into the ToricGT env, the script
    creates a separate ToricGT-named Sage env and installs a wrapper at:
      $CONDA_PREFIX/bin/sage
    for the ToricGT env.
  - Final verification runs:
      python scripts/build_toric_tropical_certificates.py --all-exact-cas --require-cas
USAGE
}

log() {
  printf '[toricgt-cas] %s\n' "$*" >&2
}

die() {
  printf '[toricgt-cas] ERROR: %s\n' "$*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)
      TORICGT_ENV="${2:?missing value for --env}"
      shift 2
      ;;
    --sage-env)
      SAGE_FALLBACK_ENV="${2:?missing value for --sage-env}"
      shift 2
      ;;
    --no-sage)
      INSTALL_SAGE=0
      shift
      ;;
    --no-macaulay2)
      INSTALL_MACAULAY2=0
      shift
      ;;
    --no-extras)
      INSTALL_EXTRAS=0
      shift
      ;;
    --no-apt-update)
      APT_UPDATE=0
      shift
      ;;
    --no-verify)
      VERIFY=0
      shift
      ;;
    --yes)
      ASSUME_YES=1
      shift
      ;;
    --no-yes)
      ASSUME_YES=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

command -v conda >/dev/null 2>&1 || die "conda is required"

CONDA_BASE="$(conda info --base)"
# shellcheck disable=SC1091
source "${CONDA_BASE}/etc/profile.d/conda.sh"

conda env list | awk '{print $1}' | grep -qx "${TORICGT_ENV}" || die "Conda env '${TORICGT_ENV}' does not exist"
TORICGT_PREFIX="$(conda run -n "${TORICGT_ENV}" bash -lc 'printf "%s" "$CONDA_PREFIX"')"
[[ -n "${TORICGT_PREFIX}" && -d "${TORICGT_PREFIX}" ]] || die "could not resolve prefix for env '${TORICGT_ENV}'"

CONDA_YES=()
APT_YES=()
if [[ "${ASSUME_YES}" -eq 1 ]]; then
  CONDA_YES=(-y)
  APT_YES=(-y)
fi

have_in_env() {
  local exe="$1"
  conda run -n "${TORICGT_ENV}" bash -lc "command -v ${exe} >/dev/null 2>&1"
}

install_wrapper() {
  local name="$1"
  local target="$2"
  local wrapper="${TORICGT_PREFIX}/bin/${name}"
  if [[ -e "${wrapper}" && ! -L "${wrapper}" ]]; then
    if ! grep -q "ToricGT CAS wrapper" "${wrapper}" 2>/dev/null; then
      die "refusing to overwrite existing non-ToricGT wrapper: ${wrapper}"
    fi
  fi
  cat > "${wrapper}" <<EOF
#!/usr/bin/env bash
# ToricGT CAS wrapper generated by scripts/install_cas_backends.sh
exec ${target} "\$@"
EOF
  chmod +x "${wrapper}"
  log "installed wrapper ${wrapper} -> ${target}"
}

install_sage() {
  if have_in_env sage; then
    log "SageMath already visible in ${TORICGT_ENV}: $(conda run -n "${TORICGT_ENV}" bash -lc 'sage --version | head -n 1')"
    return
  fi

  log "attempting SageMath install directly into Conda env '${TORICGT_ENV}'"
  if conda install -n "${TORICGT_ENV}" -c conda-forge sage gfan --solver=libmamba "${CONDA_YES[@]}"; then
    have_in_env sage || die "Sage install reported success but sage is not visible in ${TORICGT_ENV}"
    log "SageMath installed into ${TORICGT_ENV}: $(conda run -n "${TORICGT_ENV}" bash -lc 'sage --version | head -n 1')"
    return
  fi

  log "direct Sage install into '${TORICGT_ENV}' failed; creating fallback env '${SAGE_FALLBACK_ENV}'"
  if ! conda env list | awk '{print $1}' | grep -qx "${SAGE_FALLBACK_ENV}"; then
    conda create -n "${SAGE_FALLBACK_ENV}" -c conda-forge sage gfan python=3.13 --solver=libmamba "${CONDA_YES[@]}"
  else
    conda install -n "${SAGE_FALLBACK_ENV}" -c conda-forge sage gfan --solver=libmamba "${CONDA_YES[@]}"
  fi
  conda run -n "${SAGE_FALLBACK_ENV}" bash -lc 'command -v sage >/dev/null && sage --version >/dev/null'
  install_wrapper sage "conda run --no-capture-output -n ${SAGE_FALLBACK_ENV} sage"
  have_in_env sage || die "Sage wrapper was installed but sage is still not visible in ${TORICGT_ENV}"
}

install_macaulay2() {
  if have_in_env M2; then
    log "Macaulay2 already visible in ${TORICGT_ENV}: $(conda run -n "${TORICGT_ENV}" bash -lc 'M2 --version | head -n 1')"
    return
  fi

  if command -v M2 >/dev/null 2>&1; then
    install_wrapper M2 "$(command -v M2)"
    have_in_env M2 || die "M2 wrapper installed but M2 is not visible in ${TORICGT_ENV}"
    return
  fi

  if ! command -v apt-get >/dev/null 2>&1; then
    die "apt-get not found; install Macaulay2 manually and rerun"
  fi

  log "installing Macaulay2 with apt"
  if [[ "${EUID}" -eq 0 ]]; then
    if [[ "${APT_UPDATE}" -eq 1 ]]; then
      apt-get update
    fi
    apt-get install "${APT_YES[@]}" macaulay2
  else
    command -v sudo >/dev/null 2>&1 || die "sudo is required for apt Macaulay2 install"
    if [[ "${APT_UPDATE}" -eq 1 ]]; then
      sudo apt-get update
    fi
    sudo apt-get install "${APT_YES[@]}" macaulay2
  fi

  command -v M2 >/dev/null 2>&1 || die "apt Macaulay2 install completed but M2 is not on PATH"
  install_wrapper M2 "$(command -v M2)"
  have_in_env M2 || die "Macaulay2 wrapper installed but M2 is not visible in ${TORICGT_ENV}"
}

apt_install_available() {
  local packages=("$@")
  local installable=()
  local package
  for package in "${packages[@]}"; do
    if apt-cache policy "${package}" 2>/dev/null | grep -q 'Candidate: (none)'; then
      log "apt package unavailable, skipping: ${package}"
      continue
    fi
    if apt-cache policy "${package}" 2>/dev/null | grep -q 'Candidate:'; then
      installable+=("${package}")
    fi
  done
  if [[ "${#installable[@]}" -eq 0 ]]; then
    return
  fi
  log "installing apt toric/tropical support packages: ${installable[*]}"
  if [[ "${EUID}" -eq 0 ]]; then
    if [[ "${APT_UPDATE}" -eq 1 ]]; then
      apt-get update
    fi
    apt-get install "${APT_YES[@]}" "${installable[@]}"
  else
    command -v sudo >/dev/null 2>&1 || die "sudo is required for apt support package install"
    if [[ "${APT_UPDATE}" -eq 1 ]]; then
      sudo apt-get update
      APT_UPDATE=0
    fi
    sudo apt-get install "${APT_YES[@]}" "${installable[@]}"
  fi
}

install_extra_toric_tools() {
  log "checking supporting toric/tropical command-line tools"
  # These names are available on Ubuntu 24.04 universe on this workstation
  # except where the distribution omits them. apt_install_available skips
  # unavailable packages instead of failing the full CAS setup.
  if command -v apt-get >/dev/null 2>&1; then
    apt_install_available gfan normaliz topcom 4ti2 polymake singular
  fi

  # Conda-forge carries the command-line tools that do not require root on the
  # current workstation. TOPCOM is apt-only here; polymake is apt-only here and
  # requires the user's sudo path when not already installed.
  if ! have_in_env gfan || ! have_in_env Singular || ! have_in_env normaliz || ! have_in_env graver || ! have_in_env lrs; then
    conda install -n "${TORICGT_ENV}" -c conda-forge \
      gfan singular normaliz pynormaliz 4ti2 latte-integrale lrslib nauty \
      --solver=libmamba "${CONDA_YES[@]}" || true
  fi
}

verify_backends() {
  log "verifying CAS binaries in ${TORICGT_ENV}"
  conda run --no-capture-output -n "${TORICGT_ENV}" bash -lc '
    set -euo pipefail
    command -v sage
    sage --version
    command -v M2
    M2 --version
    command -v gfan
    command -v normaliz || command -v Normaliz
    command -v Singular
    command -v graver || true
    command -v hilbert || true
    command -v lrs || true
    command -v count || true
    command -v dreadnaut || true
    command -v points2triangs || true
    command -v 4ti2-zsolve || command -v zsolve || true
    command -v polymake || true
  '

  log "running ToricGT exact CAS certificate verification"
  rm -rf "${REPO_ROOT}/outputs/cas_install_check"
  conda run --no-capture-output -n "${TORICGT_ENV}" env PYTHONPATH=src \
    python scripts/build_toric_tropical_certificates.py \
      --output-dir outputs/cas_install_check \
      --num-vertices 6 \
      --all-exact-cas \
      --require-cas

  conda run --no-capture-output -n "${TORICGT_ENV}" env PYTHONPATH=src \
    python scripts/validate_cas_certificates.py outputs/cas_install_check/cache
}

main() {
  cd "${REPO_ROOT}"
  log "repo: ${REPO_ROOT}"
  log "ToricGT env: ${TORICGT_ENV} (${TORICGT_PREFIX})"
  log "disk status:"
  df -h "${REPO_ROOT}" >&2 || true

  if [[ "${INSTALL_SAGE}" -eq 1 ]]; then
    install_sage
  fi
  if [[ "${INSTALL_MACAULAY2}" -eq 1 ]]; then
    install_macaulay2
  fi
  if [[ "${INSTALL_EXTRAS}" -eq 1 ]]; then
    install_extra_toric_tools
  fi
  if [[ "${VERIFY}" -eq 1 ]]; then
    verify_backends
  fi
  log "CAS backend installation complete"
}

main "$@"
