#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONDA_BIN="${CONDA_BIN:-/home/iska/miniconda3/bin/conda}"
CONDA_ENV="${CONDA_ENV:-tokengt}"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
RUN_ID="${RUN_ID:-toricgt-oai-sidecar-bpb112-${STAMP}}"
SESSION="${SESSION:-toricgt_oai_sidecar_${STAMP}}"
WORK_DIR="${WORK_DIR:-${REPO_ROOT}/runs/oai_sidecar/${RUN_ID}}"
CHECKPOINT_DIR="${CHECKPOINT_DIR:-${REPO_ROOT}/checkpoints/${RUN_ID}}"
TRAIN_GPT="${REPO_ROOT}/amelie-iska/parameter-golf/train_gpt.py"
FINEWEB_DATA="${FINEWEB_DATA:-${REPO_ROOT}/amelie-iska/parameter-golf/data/datasets/fineweb10B_sp1024}"
TOKENIZER_PATH="${TOKENIZER_PATH:-${REPO_ROOT}/amelie-iska/parameter-golf/data/tokenizers/fineweb_1024_bpe.model}"
GRAPH_DATA_PATH="${GRAPH_DATA_PATH:-/home/iska/Documents/amelie/bio/TropicalGT/TropicalGT-I/data/toricgt/curated_hf_shards}"
WANDB_ENTITY="${WANDB_ENTITY:-amelie-iska-math}"
WANDB_PROJECT="${WANDB_PROJECT:-toricgt-parameter-golf}"
RESUME_CHECKPOINT="${RESUME_CHECKPOINT:-}"
START_STEP="${START_STEP:-0}"
ITERATIONS="${ITERATIONS:-5000}"
if [[ -n "${RESUME_CHECKPOINT}" ]]; then
  WARMUP_STEPS="${WARMUP_STEPS:-0}"
else
  WARMUP_STEPS="${WARMUP_STEPS:-20}"
fi
WARMDOWN_ITERS="${WARMDOWN_ITERS:-1200}"
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-5000}"
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-100}"
CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-5000}"
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-131072}"
VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-524288}"
TORICGT_SIDECAR_SEQ_LEN="${TORICGT_SIDECAR_SEQ_LEN:-256}"
TORICGT_SIDECAR_BATCH_SIZE="${TORICGT_SIDECAR_BATCH_SIZE:-8}"
TORICGT_SIDECAR_EVERY="${TORICGT_SIDECAR_EVERY:-1}"
TORICGT_SIDECAR_LR="${TORICGT_SIDECAR_LR:-2e-4}"
GRAPHCG_LOSS_WEIGHT="${GRAPHCG_LOSS_WEIGHT:-2e-5}"
ANALOGY_LOSS_WEIGHT="${ANALOGY_LOSS_WEIGHT:-2e-5}"
TOKENGT_GRAPH_LOSS_WEIGHT="${TOKENGT_GRAPH_LOSS_WEIGHT:-4e-5}"
TRAJECTORY_MEMORY_LOSS_WEIGHT="${TRAJECTORY_MEMORY_LOSS_WEIGHT:-2e-5}"

mkdir -p "${WORK_DIR}" "${CHECKPOINT_DIR}" "${REPO_ROOT}/training_notes/${RUN_ID}"

cat > "${REPO_ROOT}/training_notes/${RUN_ID}/LAUNCH.md" <<EOF
# ${RUN_ID}

- trainer: OAI Parameter-Golf baseline \`${TRAIN_GPT}\`
- primary BPB data: \`${FINEWEB_DATA}\`
- graph sidecar data: \`${GRAPH_DATA_PATH}\`
- tokenizer: \`${TOKENIZER_PATH}\`
- checkpoint dir: \`${CHECKPOINT_DIR}\`
- work dir: \`${WORK_DIR}\`
- resume checkpoint: \`${RESUME_CHECKPOINT:-none}\`
- start step: ${START_STEP}
- seq len: 1024
- grad accumulation: baseline fixed 8 on single GPU
- train batch tokens: ${TRAIN_BATCH_TOKENS}
- total iteration target: ${ITERATIONS}
- validation interval: ${VAL_LOSS_EVERY} steps
- checkpoint interval: ${CHECKPOINT_EVERY} steps
- sidecar active: full-rank GraphCG, analogy lattice, TokenGT causal graph loss, trajectory-memory retrieval head
EOF

COMMAND="cd ${WORK_DIR} && \
PYTHONPATH=${REPO_ROOT}/src \
PYTHONUNBUFFERED=1 \
WANDB_ENTITY=${WANDB_ENTITY} WANDB_PROJECT=${WANDB_PROJECT} WANDB_RUN_ID=${RUN_ID} WANDB_RUN_NAME=${RUN_ID} WANDB_RESUME=allow \
RUN_ID=${RUN_ID} \
DATA_PATH=${FINEWEB_DATA} TOKENIZER_PATH=${TOKENIZER_PATH} \
RESUME_CHECKPOINT=${RESUME_CHECKPOINT} START_STEP=${START_STEP} \
TORICGT_SIDECAR=1 REQUIRE_TORICGT_SIDECAR=1 GRAPH_DATA_PATH=${GRAPH_DATA_PATH} \
VOCAB_SIZE=1024 MODEL_DIM=512 NUM_LAYERS=9 NUM_HEADS=8 NUM_KV_HEADS=4 MLP_MULT=2 TIE_EMBEDDINGS=1 \
TRAIN_SEQ_LEN=1024 TRAIN_BATCH_TOKENS=${TRAIN_BATCH_TOKENS} VAL_BATCH_SIZE=${VAL_BATCH_SIZE} \
ITERATIONS=${ITERATIONS} WARMUP_STEPS=${WARMUP_STEPS} WARMDOWN_ITERS=${WARMDOWN_ITERS} MAX_WALLCLOCK_SECONDS=0 \
VAL_LOSS_EVERY=${VAL_LOSS_EVERY} TRAIN_LOG_EVERY=${TRAIN_LOG_EVERY} CHECKPOINT_EVERY=${CHECKPOINT_EVERY} CHECKPOINT_DIR=${CHECKPOINT_DIR} \
TORICGT_SIDECAR_SEQ_LEN=${TORICGT_SIDECAR_SEQ_LEN} TORICGT_SIDECAR_BATCH_SIZE=${TORICGT_SIDECAR_BATCH_SIZE} TORICGT_SIDECAR_EVERY=${TORICGT_SIDECAR_EVERY} TORICGT_SIDECAR_LR=${TORICGT_SIDECAR_LR} \
GRAPHCG_LOSS_WEIGHT=${GRAPHCG_LOSS_WEIGHT} ANALOGY_LOSS_WEIGHT=${ANALOGY_LOSS_WEIGHT} TOKENGT_GRAPH_LOSS_WEIGHT=${TOKENGT_GRAPH_LOSS_WEIGHT} TRAJECTORY_MEMORY_LOSS_WEIGHT=${TRAJECTORY_MEMORY_LOSS_WEIGHT} \
${CONDA_BIN} run --no-capture-output -n ${CONDA_ENV} python ${TRAIN_GPT} 2>&1 | tee ${WORK_DIR}/train.log"

echo "${COMMAND}" > "${REPO_ROOT}/training_notes/${RUN_ID}/command.sh"
tmux new-session -d -s "${SESSION}" "${COMMAND}"
echo "session=${SESSION}"
echo "run_id=${RUN_ID}"
echo "work_dir=${WORK_DIR}"
echo "checkpoint_dir=${CHECKPOINT_DIR}"
echo "wandb=https://wandb.ai/${WANDB_ENTITY}/${WANDB_PROJECT}/runs/${RUN_ID}"
